model: "ollama/odytrice/gemma4:4090-26b"
# model: "anthropic/claude-sonnet-4-6"
retrieve_model: "ollama_chat/odytrice/gemma4:4090-26b"  # defaults to `model` if not set
toc_check_page_num: 20
max_page_num_each_node: 10
max_token_num_each_node: 20000
if_add_node_id: "yes"
if_add_node_summary: "no"
if_add_doc_description: "yes"
if_add_node_text: "no"